import Foundation

public struct PlanetsInformation {
    
    let planetsName = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn" ,"Uranus", "Neptune"]
    
    let planetsImageMessage = ["imageMercury.png", "imageVenus.png", "imageEarth.png", "imageMars.png", "imageJupiter.png", "imageSaturn.png", "imageUranus.png", "imageNeptune.png", ]
    
    let mercuryPage = ["mercury1.jpg","mercury2.jpg","mercury3.jpg","mercury4.jpg", "MercuryFull.usdz", "Mercury is the smallest planet in our solar system. It’s a little bigger than Earth’s Moon. It is the closest planet to the Sun, but it’s actually not the hottest. Venus is hotter. Along with Venus, Earth, and Mars, Mercury is one of the rocky planets. It has a solid surface that is covered with craters like our Moon. It has a thin atmosphere, and it doesn’t have any moons. Mercury likes to keep things simple. Mercury spins slowly compared to Earth, so one day lasts a long time. Mercury takes 59 Earth days to make one full rotation. But a year on Mercury goes fast. Mercury spins slowly compared to Earth, so one day lasts a long time. Mercury takes 59 Earth days to make one full rotation. But a year on Mercury goes fast. Because it’s the closest planet to the sun, it goes around the Sun in just 88 Earth days.", "176 Earth days", "88 Earth days", "0"]
    
    let venusPage = ["venus1.jpg","venus2.jpg","venus3.jpg","venus4.jpg", "VenusFull.usdz", "Even though Venus isn't the closest planet to the Sun, it is still the hottest. It has a thick atmosphere full of the greenhouse gas carbon dioxide and clouds made of sulfuric acid. The atmosphere traps heat and keeps Venus toasty warm. It's so hot on Venus, metals like lead would be puddles of melted liquid. Venus looks like a very active planet. It has mountains and volcanoes. Venus is similar in size to Earth. Earth is just a little bit bigger.Venus is unusual because it spins the opposite direction of Earth and most other planets. And its rotation is very slow, so slow that a day in venus is equivalent to 243 Earth days. Because it's so close to the sun, a year goes by fast. It takes 225 Earth days for Venus to go all the way around the sun. That means that a day on Venus is a little longer than a year on Venus.", "225 Earth days ", "243 Earth days", "0"]
    
    let earthPage = ["earth1.jpg", "earth2.jpg","earth3.png","earth4.jpg", "EarthFull.usdz", "Our home planet Earth is a rocky, terrestrial planet. It has a solid and active surface with mountains, valleys, canyons, plains and so much more. Earth is special because it is an ocean planet. Water covers 70 percent of Earth's surface. Earth's atmosphere is made mostly of nitrogen and has plenty of oxygen for us to breathe. The atmosphere also protects us from incoming meteoroids, most of which break up before they can hit the surface. Since we live here, you might think we know all there is to know about Earth. Not at all, actually! We have a lot we can learn about our home planet. Right now, there are many satellites orbiting Earth taking pictures and measurements. This is how we can learn more about weather, oceans, soil, climate change, and many other important topics.", "24 hours", "365 days", "1"]
    
    let marsPage = ["mars1.jpg","mars2.jpg","mars3.jpg","mars4.jpg","MarsFull.usdz", "Mars is a cold desert world. It is half the size of Earth. Mars is sometimes called the Red Planet. It's red because of rusty iron in the ground.Like Earth, Mars has seasons, polar ice caps, volcanoes, canyons, and weather. It has a very thin atmosphere made of carbon dioxide, nitrogen, and argon. There are signs of ancient floods on Mars, but now water mostly exists in icy dirt and thin clouds. On some Martian hillsides, there is evidence of liquid salty water in the ground. Scientists want to know if Mars may have had living things in the past. They also want to know if Mars could support life now or in the future. Mars has two moons. Their names are Phobos and Deimos", "24.6 hours", "687 Earth days", "2"]
    
    let jupiterPage = ["jupiter1.jpg","jupiter2.jpg","jupiter3.jpg","jupiter4.jpg","JupiterFull.usdz", "Jupiter is the biggest planet in our solar system. It's similar to a star, but it never got big enough to start burning. It is covered in swirling cloud stripes. It has big storms like the Great Red Spot, which has been going for hundreds of years. Jupiter is a gas giant and doesn't have a solid surface, but it may have a solid inner core about the size of Earth. Jupiter also has rings, but they're too faint to see very well.Jupiter has a very thick atmosphere. With four large moons and many smaller moons, Jupiter forms a kind of miniature solar system, Jupiter has 79 confirmed moons. The four largest moons of Jupiter are Io, Europe, Ganymede and Callisto.", "9.93 hours", "11.86 Earth Years", "53 confirmed | 26 provisional"]
    
    let saturnPage = ["saturn1.jpg","saturn2.jpg","saturn3.jpg","saturn4.jpg","SaturnFull.usdz", "Saturn isn’t the only planet to have rings, but it definitely has the most beautiful ones. The rings we see are made of groups of tiny ringlets that surround Saturn. They’re made of chunks of ice and rock. Like Jupiter, Saturn is mostly a ball of hydrogen and helium. When Galileo Galilei saw Saturn through a telescope in the 1600s, he wasn't sure what he was seeing. At first he thought he was looking at three planets, or a planet with handles. Now we know those handles turned out to be the rings. Saturn is blanketed with clouds that appear as faint stripes, jet streams and storms. The planet is many different shades of yellow, brown and grey. Saturn is home to a vast array of intriguing and unique worlds. From the haze-shrouded surface of Titan to crater-riddled Phoebe, each of Saturn's moons tells another piece of the story surrounding the Saturn system", "10.7 hours", "29 Earth years", "53 confirmed | 29 provisional"]
    
    let uranusPage = ["uranus1.jpg","uranus2.jpg","uranus3.jpg","uranus4.jpg","UranusFull.usdz", "Uranus is made of water, methane, and ammonia fluids above a small rocky center. Its atmosphere is made of hydrogen and helium like Jupiter and Saturn, but it also has methane. The methane makes Uranus blue. Uranus also has faint rings. The inner rings are narrow and dark. The outer rings are brightly colored and easier to see. Like Venus, Uranus rotates in the opposite direction as most other planets. And unlike any other planet, Uranus rotates on its side. One year on Uranus is the same as 84 years on Earth. That’s a long time to wait for a birthday cake. Uranus has 27 known moons. All of Uranus' inner moons appear to be roughly half water ice and half rock. The composition of the outer moons remains unknown, but they are likely captured asteroids.", "17 hours 14 minutes", "84 Earth years", "27"]
    
    let neptunePage = ["neptune1.jpg","neptune2.jpg","neptune3.jpg","neptune4.png","NeptuneFull.usdz", "Neptune is dark, cold, and very windy. It's the last of the planets in our solar system. It's more than 30 times as far from the sun as Earth is. Neptune is very similar to Uranus. It's made of a thick fog of water, ammonia, and methane over an Earth-sized solid center. Its atmosphere is made of hydrogen, helium, and methane. The methane gives Neptune the same blue color as Uranus. Neptune has six rings, but they're very hard to see.Neptune is encircled by six rings. Neptune has such a long journey around the Sun it takes 165 Earth years to go around once. That’s a long year!. Neptune has 14 known moons. Neptune's largest moon Triton wasNeptune has 14 known moons. Neptune's largest moon Triton is the only large moon in the solar system that circles its planet in a direction opposite to the planet's rotation (a retrograde orbit), which suggests that it may once have been an independent object that Neptune captured", "16 hours", "165 Earth years", "14"]
    
    var planetsPages = [Array<String>]()
    
    init() {
        planetsPages = [mercuryPage, venusPage, earthPage, marsPage, jupiterPage, saturnPage, uranusPage, neptunePage]
    }
    
    
}
